FROM node:lts-alpine

WORKDIR /frontend/customer-ui

COPY customer-ui/package.json .

COPY customer-ui/yarn.lock .

RUN yarn install

COPY ./customer-ui .

COPY ./share ../share

RUN ls

RUN yarn build

EXPOSE 8080

ARG BASE_URL
ENV HOST=0 
ENV PORT=8080 
ENV BASE_URL=${BASE_URL}
CMD [ "yarn", "start" ]
