version: "3.1"
services:
  api-service:
    build: 
      context: ./api-service/.
      dockerfile: ./src/main/docker/Dockerfile.jvm
      args:
        db_kind: postgresql
        DB_USERNAME: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOSTNAME: db
        DB_PORT: 5432
        DB_DATABASE: resify
        auth_url: http://auth:4321
    ports: 
      - "8081:8080"
    depends_on:
      - db
      - auth
    environment:
      db_kind: postgresql
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOSTNAME: db
      DB_PORT: 5432
      DB_DATABASE: resify
      auth_url: http://auth:4321
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: resify
    ports:
      - "5432:5432"
  auth:
    build: ./mock-oauth-server
    ports:
      - "4321:4321"
    environment: 
      host: localhost
  customer-ui:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile_customer-ui
    ports:
      - "5000:5000"
  admin-ui:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile_admin-ui
    ports:
      - "4200:8080"
