/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:f1bda1df-a099-4134-95de-1b1c4deb1c22",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_AXmKyWWqL",
    "aws_user_pools_web_client_id": "2e3f1831iuvjaf34kfov3dbt4q",
    "oauth": {
        "domain": "resify-dev.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "email",
            "openid"
        ],
        "redirectSignIn": "https://app.resify.de/",
        "redirectSignOut": "https://app.resify.de/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
